name: Android Release

on:
  release:
    types: [created]

env:
  KEYSTORE_FILE: reparto.keystore

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      
    - name: Create Keystore from Secrets
      run: |
        echo "${{ secrets.KEYSTORE }}" | base64 --decode > $KEYSTORE_FILE
        
    - name: Make gradlew executable
      run: chmod +x gradlew
      
    - name: Build Release APK
      run: |
        ./gradlew assembleRelease
        ls -la app/build/outputs/apk/release/
        
    - name: Upload APK to Release
      uses: softprops/action-gh-release@v1
      with:
        files: app/build/outputs/apk/release/*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
